"""create shipping table

Revision ID: 0c87cd21230e
Revises: a64ee97e8712
Create Date: 2021-09-25 22:57:14.520850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c87cd21230e'
down_revision = 'a64ee97e8712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('port_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('port_code')
    )
    op.create_table('ship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('shipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_port', sa.Integer(), nullable=False),
    sa.Column('to_port', sa.Integer(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['from_port'], ['port.id'], ),
    sa.ForeignKeyConstraint(['to_port'], ['port.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment')
    op.drop_table('ship')
    op.drop_table('port')
    # ### end Alembic commands ###
