"""add created and updated to shipping table

Revision ID: 7a708d5b1cbe
Revises: 0c87cd21230e
Create Date: 2021-09-26 11:34:09.641787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a708d5b1cbe'
down_revision = '0c87cd21230e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('port', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('port', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'port', ['id'])
    op.add_column('ship', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('ship', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'ship', ['id'])
    op.add_column('shipment', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('shipment', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'shipment', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='unique')
    op.drop_column('shipment', 'updated')
    op.drop_column('shipment', 'created')
    op.drop_constraint(None, 'ship', type_='unique')
    op.drop_column('ship', 'updated')
    op.drop_column('ship', 'created')
    op.drop_constraint(None, 'port', type_='unique')
    op.drop_column('port', 'updated')
    op.drop_column('port', 'created')
    # ### end Alembic commands ###
